
server:
  port: 8009
  
spring:  
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://edu-mysql-data-svc.default.svc.cluster.local:3306/blackstar?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/blackstar?autoReconnect=true&useUnicode=true&characterEncoding=utf8
  
    username: blackstar
    password: 1234
    maxIdle: 20
    maxActive: 400
    maxWait: 10000
    validationQuery: SELECT 1
  
  redis:
    host: 127.0.0.1
#    host: redis.default.svc.cluster.local
    port: 6379
    timeout: 50
    
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  mapper-locations: classpath:mapper/board*.xml