apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: edu-api
spec:
  selector:
    app: edu-api
  ports:
  - protocol: TCP
    port: 8009
    nodePort: 30001
  type: NodePort
  





---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edu-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: edu-api
        version: v1
    spec:
      containers:
      - name: edu-api
        image: gcr.io/api-project-296757883911/edu-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8009
 
